Syn 163 show statistics of a trace
synthchron/synthchron pull request #258
Opened 2023-05-23 13:20 UTC by MathiasBoi6

## Describe your changes
Simulation results don't need to wait for arbitrary loading.
This PR mostly involves the analysis panel

# Stats:
Amount of traces | Amount of events
Amounts of each event

## Checklist before requesting a review
- [x] I have performed a self-review of my code

2023-05-23 18:08 UTC, Volume999 commented
Once the Mass generation of traces is merged to main, you will have to change a lot of things here, I reckon? So merging this would not really be a wise thing right now I think

2023-05-23 18:28 UTC, Volume999 requested changes

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/PostProcessing.tsx
> +export function XESlogToString(log: XESLog) {
Pascal Case

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/AnalysisPanel.tsx
> +  const DoughnotData = AggregateToData(aggregateOfLog, chartType.Doughnot)
Typo + camel case

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/analysisFunctions/aggregateCharts.tsx
> +type logAggregate = Map<string, number> //Map<key, value>
Pretty sure types are pascal case

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/analysisFunctions/aggregateCharts.tsx
> +type doughnotData = {
typo and pretty sure pascal case

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/analysisFunctions/aggregateCharts.tsx
> +type defualtData = {
typo

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/analysisFunctions/aggregateCharts.tsx
> +  Doughnot,
typo and I think enums are also pascal case?

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/analysisFunctions/aggregateCharts.tsx
> +type dataset = doughnotData | defualtData
Pascal case I think

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/analysisFunctions/aggregateCharts.tsx
> +type chartData = {
also Pascal Case

2023-05-23 18:28 UTC, Volume999 commented on packages/synthchron-tauri/src/components/editor/bottomDrawer/analysisFunctions/aggregateCharts.tsx
> +//REMOVE EXPORT
you didn't remove export

2023-05-23 18:29 UTC, Volume999 requested changes
Ultimately, you will also have to merge it with the mass trace generation PR in order to start fully evaluating your PR

2023-05-28 11:34 UTC, MathiasBoi6 commented
Making a link to this image so i can reference it in my code :)
![image](https://github.com/synthchron/synthchron/assets/79922317/910ad5ea-c16d-49ba-9be9-223ec64d33eb)

2023-05-28 15:46 UTC, leny-mi approved these changes
lgtm!

2023-05-29 10:57 UTC, Volume999 approved these changes

2023-05-29 11:01 UTC, merged